### ISSUE TITLE
New datasetFill option

### ISSUE THREAD

**Issue by Wikunia** [FVANCOP/ChartNew.js#119]
I would like to add something like this:
![climate](https://cloud.githubusercontent.com/assets/4931746/3840536/1f59212a-1e1f-11e4-823e-e022a4ccfda2.png)
Don't know how to call the options for that :) Maybe two options for this striped datasetFill and one for the blue-red-change.

**Comment by FVANCOP** [comment]
A new Add-ins has been created and the code has been updated so that you can now create charts like this : 

![900_080_hatch1](https://cloud.githubusercontent.com/assets/6121933/11195664/5e4247d2-8cb3-11e5-9d97-34b0d52adefd.png)

See : https://github.com/FVANCOP/ChartNew.js/wiki/900_080_hatch.js

This is also a solution for issue #119
