### ISSUE TITLE
draw bar with function not working properly

### ISSUE THREAD

**Issue by itknowlogics** [FVANCOP/ChartNew.js#221]
Hi FVANCOP,

I'm trying to draw a bar (Fill and Stroke) with different colors if the value of the data is below or above from x number using the option function in the wiki documentation and always show me the same color. This is my code. I'm doing something wrong?

function setColor(area, data, config, i, j, animPct, value, typegraph, ctx, v0, v1, v2, v3) {
                if (area == "COLOR") {
                    if (value < 50) return ("rgba(218,40,16,0.5)");
                    else return ("rgba(24,152,0,0.5)");
                }
                if (area == "STROKECOLOR") {
                    if (value < 50) return ("rgba(218,40,16,1)");
                    else return ("rgba(24,152,0,1)");
                }
            }

var data =
                {
                    labels: ["Coordinador Luis Antonio", "Hernan Andres", "Leidy Roció", "Mauricio", "Mayuri", "Brian", "Paola Andrea", "Víctor", "Erika Yolanda", "Yuly Fernanda"],
                    datasets:
                        [
                            {
                                fillColor: setColor,
                                strokeColor: setColor,
                                data: [21, 16, 44, 60, 110, 50, 32, 22, 19, 35],
                                title: "Cerrados"
                            }
                        ]
                }

**Comment by FVANCOP** [comment]
Since version 2 of ChartNew.js, the parameters passed to the function have changed. The wiki documentation has been updated - Where did you find this ???? - see : https://github.com/FVANCOP/ChartNew.js/wiki/130_option_functions).

For your sample, just change the setColor function to this : 


function setColor(area, ctx, data, statData, posi, posj, othervars) {
if (area == "COLOR") {
if (data.datasets[posi].data[posj] < 50) return ("rgba(218,40,16,0.5)");
else return ("rgba(24,152,0,0.5)");
}
if (area == "STROKECOLOR") {
if (data.datasets[posi].data[posj] < 50) return ("rgba(218,40,16,1)");
else return ("rgba(24,152,0,1)");
}
}

**Comment by itknowlogics** [comment]
Hi,

I found this in the same link you show me in your comment and i still see the older wiki, because is the same code i show you in my issue. Anyway your solution work perfectly and solve my problem. Thank you for your help. I will close this issue ;)
