### ISSUE TITLE
Bar chart with single dataset: percentage calculation error

### ISSUE THREAD

**Issue by HaoyunS** [FVANCOP/ChartNew.js#229]
Hi,

It seems that, if you only have one dataset for a bar chart, and would like to calculate the percentage for each bar, the function for v6 is not correct. (It will show 100% for each bar.)

Thanks!

**Comment by FVANCOP** [comment]
It is not an error : v6 is the percentage of the group of bar; Because each group has only 1 bar, all bar have a percentage of 100 %.... But, of course, it is not what you want.

In the new version uploaded today, I have added 3 new variables : 

v6T -> Percentage of the full data 
percentageT : idem variable v6T but not formatted;
grandtotal : total of all the data.

For your graph, you should use v6T in the template instead of v6 (annotateLabel and/or inGraphDataTmpl options to be changed).

annotateLabel: "<%=(v1 == '' ? '' : v1) + (v1!='' && v2 !='' ? ' - ' : '')+(v2 == '' ? '' : v2)+(v1!='' || v2 !='' ? ':' : '') + v3 + ' (' + v6T + ' %)'%>"

**Comment by HaoyunS** [comment]
Thanks!
Will check out the new v6T variable in the js file. Tried to modify the function for v6 but failed.
