### ISSUE TITLE
[Annotations] Falling off right of viewport

### ISSUE THREAD

**Issue by wezley98** [FVANCOP/ChartNew.js#238]
Hi,

If I have a line graph with annotations, the annotations will fall off the page on the far right, this means you can't see the data in the label. Is there a fix/workaround for this so if there isn't enough space to display the label it floats to the left of the data point?
![label](https://cloud.githubusercontent.com/assets/1488209/6168834/9a4182ca-b2c0-11e4-8ca8-773253b063e2.png)

**Comment by FVANCOP** [comment]
Can you check if the problem is solved with the last version ?

**Comment by wezley98** [comment]
Hi,

Thanks it works great.

**Comment by FVANCOP** [comment]
Unfortunately, the fix is not correct when the annotate is not a simple line...

I was forced to add a new option : annotateRelocate. Set it to true (default value is false), if you want that the annotate is displayed entirely on the screen. Use this option only if the annotate is a simple text on a single line.
