### ISSUE TITLE
Add html inside annotate ?

### ISSUE THREAD

**Issue by Oxyxy** [FVANCOP/ChartNew.js#240]
I was wondering if it was possible to write some html inside "annotateLabel". I already called a function who return the data that I need but I wanted to know if there is a way to add html (css class) properly.
At this moment the html tags seems to break the code, I mean the annotate is displayed far from the cursor when I tried to add a tag.

Examples:
"div" create the same effect as a "br"
"span" works but the annotate is not displayed fined (far from the cursor)

The final Goal is to add colors inside annotate "span class="my-color-class""
Thanks for your feedback ;-)

**Comment by FVANCOP** [comment]
You point out a problem introduced with the last fix (for issue #238) : when the annotate is not a simple text line, it could appear far from the mouse. The problem has been fixed in the last available version.

With the new version, the "span" in the annotate should be displayed on the right place.

About your question: the annotate is a "div". You can put in it a code allowed by "div". 
In the Samples folder, I have added a new member : div_in_annotate.html. This is a sample of a div inside the annotate div. You will see that you can change the background color of the included div. I think that this is what you want. I suppose that you can achieve a similar result with "span".

**Comment by Oxyxy** [comment]
Many thanks ;-) it works great now !
