### ISSUE TITLE
Problem with pie and stacked bar

### ISSUE THREAD

**Issue by bhavyamanasa** [FVANCOP/ChartNew.js#265]
hi,
i have problem with pie and stack bar charts in my page.

the following pic shows date range for one week. it works fine for one week, it shows both values PJP(red color) and achieved(green color). 

![pic32](https://cloud.githubusercontent.com/assets/11133804/6879879/2a3d2ca0-d538-11e4-8928-bd2b1d8ba052.png)
 If i select single date then it should show both red and green,but it is showing only green(achieved)

![pic30](https://cloud.githubusercontent.com/assets/11133804/6879902/45438b7e-d539-11e4-9456-f164a3211861.png)

**Comment by FVANCOP** [comment]
For the stacked bar, you have to force the minimum value to display. For instance graphMin:0;

For the Pie, I do not understand what happens.... and I cannot reproduce it. It could be that in your case a variable is considered as global instead of unique for each chart. But if I cannot reproduce it, it is difficult to help you.

In the sample folder, I have added the issue265.html where I have reproduced your data and where everything seems OK; 

If you want some help for debugging the problem with the Pie, can you send me the source of your program to my mail address ?

Regards,
François
