### ISSUE TITLE
problem with logarithmic plot

### ISSUE THREAD

**Issue by thestick613** [FVANCOP/ChartNew.js#270]
https://jsfiddle.net/dneftd7v/

for some values, this happens, the graph's maximum Y value is calculated wrong.

**Comment by FVANCOP** [comment]
Sorry for the long delay before you got an answer. Busy with other things.

logarithmic scale is not easy to implement (this was initially implemented by @Wikunia but I made lot of changes and I thing that bugs came with one of the changes). A little change has been performed; Can you download the last version and try if the problem is solved ?

Regards,
François

**Comment by thestick613** [comment]
It's still not working: https://jsfiddle.net/dneftd7v/1/embedded/result/
BTW great library, and thanks for your effort.

**Comment by FVANCOP** [comment]
Oups - Sorry, my change was not sufficient. The last version should be better (fix integrated in the last version) :-)

**Comment by thestick613** [comment]
Fixed. Thanks again!
