### ISSUE TITLE
LineChart with only one point!

### ISSUE THREAD

**Issue by GuyGreen** [FVANCOP/ChartNew.js#279]
In my site I create line charts based on dynamic data, If  the data contains only one point the chart fails to generate the x axis.

example:
![chart](https://cloud.githubusercontent.com/assets/11877642/7451200/af487cca-f256-11e4-91d8-d5ccd29cef74.png)

**Comment by GuyGreen** [comment]
OK, I managed to fix this issue on the version I downloaded... 

the problem was with the line:
```javascript
valueHop = Math.floor(msr.availableWidth / (data.labels.length - 1));
```

the label's length is 0 and so the result is Infinity.

Fix: 
```javascript
var toDivide = (data.labels.length - 1 > 0) ? data.labels.length - 1 : 0;
valueHop = toDivide != 0 ? Math.floor(msr.availableWidth / toDivide) : 0;
```
And to make sure that msr.availableWidth doesn't get messed up I changed:
```javacript
msr.availableWidth = (data.labels.length - 1) * valueHop;
```
To:
```javascript
msr.availableWidth = data.labels.length > 1 ? (data.labels.length - 1) * valueHop : msr.availableWidth;
```

**Comment by FVANCOP** [comment]
Sorry for the long delay before you got an answer.

I don't understand how you could get this issue (unless the array variable labels is not initialized correctly - for instance if you put <B><I> labels : "" </B></I> instead of  <B><I> labels : [""] </B></I>), because when there is only one point, data are reworked so that 2 other points are added with following code (line 2747) : 

		// adapt data when length is 1;
		var mxlgt = 0;
		for (var i = 0; i < data.datasets.length; i++) {mxlgt = Max([mxlgt, data.datasets[i].data.length]);}
		if (mxlgt == 1) {
			if (typeof(data.labels[0]) == "string") data.labels = ["", data.labels[0], ""];
			for (i = 0; i < data.datasets.length; i++) {
				if (typeof(data.datasets[i].data[0] != "undefined")) data.datasets[i].data = [undefined, data.datasets[i].data[0], undefined];
			}
			mxlgt=3;
		}

With this additional code, you got following chart : 

![canvas](https://cloud.githubusercontent.com/assets/6121933/8116243/332d0ec8-1081-11e5-99b1-180648d43d8a.png)
