### ISSUE TITLE
Chart labels with more than 30 characters causes chart rendering problem

### ISSUE THREAD

**Issue by danielplappert** [FVANCOP/ChartNew.js#281]
Hi, I came across a problem using long chart labels. The problem is, that these chart labels can be longer then 30 characters (this is something I can not control) . If this is the case, no chart will be rendered. There is no javascript error, the canvas area is just blank.

The problem is, just shorten the labels won't help, because it is not clear then, what is meant by it. Adding an annotation label to this chart won't help either, because the label has the same (shorten) value.

It is possible, that these long labels will be shorten by ChartNew.js? In case a label is longer than 30 characters, it will be shorten, but the full label will be used for the annotation labels!?

Thanks in advance,
best regards,
Daniel

**Comment by FVANCOP** [comment]
Hi,

The chart is not rendered because there is no space enough to draw it.

For long labels, you can split them on several lines. See https://github.com/FVANCOP/ChartNew.js/wiki/160_Line_break

The break lines can be generated through a format. Also you can truncate the labels on the X axis with a format. See https://github.com/FVANCOP/ChartNew.js/wiki/100_050_Format

Hope it helps,
François

**Comment by danielplappert** [comment]
Hi,
thanks for your help. I inserted a line break, the display problem is solved now.

Best regards,
Daniel
