### ISSUE TITLE
Different inGraphDataPaddingY by Line

### ISSUE THREAD

**Issue by ulysnep** [FVANCOP/ChartNew.js#322]
Hi!

I'm having trouble with displaying in graph data due to overlapping lines on the line chart. Is there a work around for this or is there a way to display different inGraphDataPaddingY by line?

Thanks!

![overlapping_lines](https://cloud.githubusercontent.com/assets/8585209/8466295/f3bb8f5a-2005-11e5-9668-dd919cab5a40.png)

**Comment by FVANCOP** [comment]
Instead of specifying a unique value for an option, you can specify an array of value (this is not true for all options, but for the ones where there is an utility to have that feature); In that case, the first value in the array is for the first line; the second value, for the second line ; etc...

See : https://github.com/FVANCOP/ChartNew.js/wiki/085_option_array_func

For your sample, I should not play with the only option inGraphDataPaddingY, but : 

     inGraphDataVAlign: ["top","bottom"],
     inGraphDataPaddingY: [-3,3],

For the inGraphData options, "array of values" is implemented; But If you have an option for which "array of values"  is not implemented, justify why you need it via an issue and I will implement it :-)

**Comment by ulysnep** [comment]
Excellent! Thank you for responding so quickly. I'll look into the "array of values" more to see if I can solve my use case.

Thanks again!

**Comment by ulysnep** [comment]
I'm not sure where I'm going wrong. I've added the values above, but it they don't seem to change the graph. I have three lines so I adjusted the array to include the third line. I'm using the chartnew.js from about 3 weeks ago. 

![pastedgraphic-2](https://cloud.githubusercontent.com/assets/8585209/8917774/fdc0408c-3468-11e5-9407-c0234ce622fb.png)

Below are the configs that I'm using:

      animationStartWithDataset : startWithDataset,
      animationStartWithData : startWithData,
      animationSteps : 50,
      canvasBorders : false,
      legend : true,
      legendBorders : false,
      inGraphDataShow : true,
      annotateDisplay : true,
      graphTitleFontSize: 18,
      scaleOverride : true,
      scaleStartValue : 0,
      scaleSteps : 5,
      scaleStepWidth : 5,
      scaleGridLineColor : "rgba(0,0,0,0)",
      scaleLineColor : "rgba(0,0,0,0)",
      inGraphDataVAlign: ["top","top","bottom"],
      inGraphDataPaddingY: [3,3,-3],
      scaleGridLineColor : "#fff",
      datasetFill : false,
      legendBlockSize : 20,
      scaleLabel: "$<%=value%>",
      inGraphDataTmpl: "$<%=v3%>",
      mouseDownLeft : fctMouseDownLeft

**Comment by FVANCOP** [comment]
A bug was introduced with the fix for issue 205. It has been fixed in the last version and should now work has it should with those options  (your program is correct).

Sorry for the delay : I was on holiday :-)

**Comment by ulysnep** [comment]
Works now, thank you!

No need to apologize, you completely deserve it just based on your quick and helpful response. Thanks again!
