### ISSUE TITLE
The chart is getting bigger after update

### ISSUE THREAD

**Issue by ssarnecki** [FVANCOP/ChartNew.js#324]
I've got a stacked bar chart with two options (month and day view).
Each time I was pushing buttons to update chart, canvas became two times bigger.

Only solution I made was to remove canvas and then paste it again by append()..

**Comment by FVANCOP** [comment]
@ssarnecki  : I ask you to open a new issue because the description you made in issue #213 was "The legend is gone after update don't know why". What is your issue ? Problem with legend or the size of the chart ??? If it is only the size of the chart, it has to be related in issue #213 (for which I have no solution up to now); If it is a legend problem, then describe the legend problem in a new issue (I will close this one because it is the same as issue #213 )... If you have both problems, separate them in two issues : a new one for the legend problem and issue #213 for the chart that is changing in size after an update.
