### ISSUE TITLE
Odd-looking part of legend text

### ISSUE THREAD

**Issue by leesuit** [FVANCOP/ChartNew.js#330]
Hi!
I am displaying pie chart with legend on the right side of the graph (legendPosY: 2, legendPosX: 3) and noticed chart and legend overlapping when resizing screen.
![chartnew_1](https://cloud.githubusercontent.com/assets/13274639/8619858/d0af963e-271a-11e5-88c8-96eda17c70c2.png)
So I used spaceRight : 150 and legendXPadding : 150 together. And noticed that part of legend text is looking odd. The part that is out of offset region (exactly 150px).
![chartnew_2](https://cloud.githubusercontent.com/assets/13274639/8619947/39aa8242-271c-11e5-8374-5b7942cb1a6b.png)
Thanks a lot, great work!

**Comment by FVANCOP** [comment]
Oups... I know what is the problem, but there is no solution to solve it in current version. I come back soon with a solution (through a new option)

**Comment by leesuit** [comment]
If I may make a suggestion, perfect solution will provide option to move pie chart to the left or right without moving legend and title. Thanks for quick response

**Comment by FVANCOP** [comment]
I've tryed to implement it ... but it was already implemented (I forgot that.....). I found some issues which are fixed in the last version.

Set option legendPosX to 0 if you want to display the legend at the left of the chart; set it to 4 if you want to display the legend at the right of the chart.

     legendPosX : 4

https://github.com/FVANCOP/ChartNew.js/wiki/100_090_Legend#legendposx

**Comment by leesuit** [comment]
yea, works perfect, thank you
