### ISSUE TITLE
Is there a way to have a chart background by value on the Radar chart ?

### ISSUE THREAD

**Issue by trollfot** [FVANCOP/ChartNew.js#335]
I'm looking for a way to add a color for each value "slice" on the radar chart.
Example : a radar chart numbering 1 to 10, 1 has blue BG, 2 green BG, 3 pink BG...
Is there a current way to do it ? Is it doable ?

**Comment by FVANCOP** [comment]
Radar chart do not have "slices" but a unique area for a full dataset. So, the response is "no" because there are no slices...

"Slices" are well defined for PolarArea, Pie and Doughnut. For those charts, yes, you can assign a color in function of the value.

To do this, do not define any color in the data; create a function (for instance assignColorFromValue) and set this function as value for option "defaultFillColor".


          var mydata = [
          	{
          		value : 1,
          		title : "data1"
          	},
          	{
          		value : 3,
          		title : "data2"
          	},
          	{
          		value : 2,
          		title : "data3"
          	}
          ]

          function assignColorFromValue(area, ctx, data,statData, posi,posj,othervars){
          	switch(parseInt(data[posi].value)) {
          		case 0 : rtcolor="blue"; break;
          		case 1 : rtcolor="red"; break;
          		case 2 : rtcolor="yellow"; break;
          		case 3 : rtcolor="pink"; break;
          		case 4 : rtcolor="rgba(255,255,0,0.5)"; break;
          		default : rtcolor="rgba(255,0,255,0.5)"; break;
          	}
          	return rtcolor;
          }
 
          var myLine = new Chart(document.getElementById("canvas_pie").getContext("2d")).Pie(mydata,{defaultFillColor : assignColorFromValue});


For functions associates to options see https://github.com/FVANCOP/ChartNew.js/wiki/085_option_array_func
