### ISSUE TITLE
Couple of small issues with stacked bars

### ISSUE THREAD

**Issue by gavinspearhead** [FVANCOP/ChartNew.js#373]
It seems that in case of a stackebar it doesn't use the full height (or ~90% of it), but roughly only half of the height. 

Also at some point the width of the bars seems to diminish to about half of it. Still using the same code as before. 

The first pic below is only singl bar. The second stacks 6 bar and the last one stacks 30. Some (about half actually) of the values are 0. 

![singlebar](https://cloud.githubusercontent.com/assets/5463588/10554471/1683b2c6-7464-11e5-8291-a317e5fe9dfd.png)
![multistack1](https://cloud.githubusercontent.com/assets/5463588/10554474/191e1120-7464-11e5-996b-4b73992a4f6a.png)
![multistack2](https://cloud.githubusercontent.com/assets/5463588/10554480/1c63f034-7464-11e5-8c45-9c100a8300b0.png)

**Comment by FVANCOP** [comment]
The height is correctly computed (as designed), but I agree that it is not really nice in your sample; If you set option "graphMaximized : true", it will be better.

The problem of the bar width has been fixed in the last version.

Thanks for reporting the problem and for using ChartNew.js,
François

**Comment by gavinspearhead** [comment]
Thanx again. Both issues are fixed.
