### ISSUE TITLE
Using animation with background crossImage

### ISSUE THREAD

**Issue by Bambicruz** [FVANCOP/ChartNew.js#374]
Is there any fix or workaround to have animation work with the background crossImage?

**Comment by FVANCOP** [comment]
There is a bypass in some limited cases that's why I prefer to say that it is not possible.

The proposed "bypass" will not work in association with some options : there are lot of limitations. One of the limitations is that you can not use "rgba" colors. For all those reasons, I prefer to say that it is not possible, but if you really want a result try this ...

In the shape definition, set   ' when : "always" '

In the options, set the (not documented option) "clearRect: false". Preferably, you should also define a linear animation (set option ' animationEasing: "linear", ).

If it does not work, try to reduce the options not assigned to their default value.

**Comment by Bambicruz** [comment]
Thanks Francois, I will try it and let you know.
