### ISSUE TITLE
transparent lines between chart pieces in pie chart

### ISSUE THREAD

**Issue by omarsedki** [FVANCOP/ChartNew.js#389]
when there are no segment in chart settings.still there transparent line width:1px between chart pieces
here is a sample for the problem

http://charts.livegap.com/chart.php?user=omar.sedki&title=probleminChart_01&folder=/

**Comment by FVANCOP** [comment]
Hi Omar,

Unfortunately, I have no good news for you; I've tryed lot of things, but none gives a good solution. I have performed a similar test with Chart.js and I got the same very small lines. I thing that this is more a "bug" of the "arc" function : If you put two arcs next to each other (same center; end angle of the  first arc = start angle of the second arc) you will always have this problem.

In your sample, if you set following options, those small lines will not appear, but the result is not really the same...

	segmentShowStroke : true,
	segmentStrokeColor : "#333",
	segmentStrokeWidth :1,

Your Chart : 
![probleminchart_01](https://cloud.githubusercontent.com/assets/6121933/11319618/5637797c-907d-11e5-9a17-89d360d5bc2d.png)

The chart with the proposed options : 

![canvas](https://cloud.githubusercontent.com/assets/6121933/11319614/1cddfa34-907d-11e5-9271-a316a7ca46fb.png)

**Comment by omarsedki** [comment]
Hi Francois 
thanks for your  fast reply.
i try with add  segment stroke(1.5 px) with the  color of the segment when segmentShowStroke=false
and it work for me.
also please Donaugh chart not working with gradient colors.

Thanks 
Omar Sedki

**Comment by omarsedki** [comment]
Here What I add

if (!config.segmentShowStroke) {
						ctx.lineWidth =1.5;
						ctx.strokeStyle =setOptionValue(1,"COLOR",ctx,data,statData,data[i].color,config.defaultFillColor,i,-1,{animationDecimal: animationDecimal, scaleAnimation : scaleAnimation} );
						ctx.setLineDash([]);
						console.log(config);
						ctx.stroke();					 
						ctx.setLineDash([]);
					}

**Comment by FVANCOP** [comment]
Hi Omar, 

I've tryed your proposed code : you're right and it is a good solution but ... if you look carefully to the produced chart, you will see that the color on the border is displayed twice darker compared to the inside color. But I agree : it is better that what we got previously.

Unfortunately I could not merge the branch. I have reproduced a similar code. In the implemented code, you have to set option ' segmentShowStroke : "merge" ' instead of  ' segmentShowStroke : false '.  (if you set option segmentShowStroke : false you will get the same result as before the last change).

In the code, I have set "lineWidth" to 0 which is a non sense. But....... it works. I really think that there is a bug in the arc function. Perhaps that it will be solved in a future version of the browsers.

For the second related problem (gradientColor not working for Doughnut), I did not check a lot but there is a incompatibility between the code and the "http://charts.livegap.com/js/webfont.js" ; If found two bypass for this problem : 
* Solution 1 : remove the include of http://charts.livegap.com/js/webfont.js;
* Solution 2 : simply rename your option variable ChartOptions to MyChartOptions

**Comment by omarsedki** [comment]
Thanks  alot Francois .i think segmentShowStroke : "merge" is a very good solution. For the second problem i think it from my site. Thanks alot
