### ISSUE TITLE
Dynamic chart size / Fixed bar-chart bar thickness

### ISSUE THREAD

**Issue by mmc071** [FVANCOP/ChartNew.js#416]
Hi,

Is there any way to fix the bar size (vertical thickness) on a horizontal bar chart and have the chart automatically resize itself to accomodate all the bars without squashing them?

Situation is that i have data coming from a database and i dont know how many items are going to be returned and i need to display all of them. It might be 5 items on some occassions, it might be 20 on another. 

Example below... The 3 charts will be displayed together on the same page below one another so it makes visual sense for the bar thickness to be consisent and the chart height to vary accordingly.

Thanks
Martin

![chart](https://cloud.githubusercontent.com/assets/17247376/13178899/201960b6-d719-11e5-9556-e772cab8a4b0.jpg)

**Comment by FVANCOP** [comment]
Hi,

Fixing the bar width is not implemented because it is more related to the canvas height.; 

In the sample folder, you will find the "resize_canvas.html"; You can apply the same idea for horizontal bars; Change "canvas.width" to "canvas.height" in the resizeCanvas function and try to find the ad-hoc values that fits for your chart.

François
