### ISSUE TITLE
How can I do scalable Doughtnut chart, when I highLight?

### ISSUE THREAD

**Issue by notemka** [FVANCOP/ChartNew.js#417]
Hi Fvancop, 
how can I do like this: http://joxi.ru/E2pgN9OSBYNb4m ? Please, help me. I didn't find necessary options on this page: https://github.com/FVANCOP/ChartNew.js/wiki/100_25_highLight.
Thank you.

**Comment by markosko** [comment]
I am not sure what u mean by scalable chart but its should be this https://github.com/FVANCOP/ChartNew.js/wiki/100_25_highLight#highlightset and try use option `highLightSet : { expandOutRadius : 0.10, expandInRadius : -0.10 }`
 and change values of these two parameters

**Comment by notemka** [comment]
I used this option `highLightSet : { expandOutRadius : 0.10, expandInRadius : -0.10 }` but it has not helped

**Comment by markosko** [comment]
Options should work but values 0.10 and -0.10 are used by default which are on picture what u send so if u want to change like to make it bigger try `highLightSet : { expandOutRadius : 0.50, expandInRadius : -0.50 }` but expandOutRadius and expandInRadius options work only for pie and doughnut if u use these options on other types it wont work but if u want u can send me mail with your whole options and data so we wont spam other people or maybe there is error in script somewhere which is why it is not working, my mail is shown in profile
