### ISSUE TITLE
Animation with new data in same time

### ISSUE THREAD

**Issue by jeremybarbet** [FVANCOP/ChartNew.js#59]
Hi!

I have an array who contains all my data to display to the graph. When I click on a button, there had been new data added to the array.

There is any solution to animate the graph to display the new data at the same moment right after this event click ?

**Comment by soodrah** [comment]
Hi Fvancop
Thanks for adding this great feature. This allows me to tell from which data to start animation with. 
Except there is one problem, it does not work with animationLeftToRight:true. 
Here is my explanation based on example animation_lines.html. Here is the dataset

datasets : [
		{
			fillColor : "rgba(220,220,220,0.5)",
			strokeColor : "rgba(220,220,220,1)",
			pointColor : "rgba(220,220,220,1)",
			pointstrokeColor : "yellow",
			
			data : [95,53,99,,73,27,82],
//			data : [40],

      title : "2014"
		},
		{
			fillColor : "rgba(151,187,205,0.5)",
			strokeColor : "rgba(151,187,205,1)",
			pointColor : "green",
			pointstrokeColor : "yellow",
			data : [35,43,59,,31,50,66],
//			data : [35],
      title : "2013"
		}
	]

I have updated the var opt1 (see below), you will notice that I have set animationStartwithData to 7 meaning I want only the last portion of the data to be animated, ie 66 from [35,43,59,,31,50,66]. This works fine as long as I do not use animationLeftToRight, as soon as I use animationLeftToRight  then portion of the graph  for value 66 does not show any  left to right animation but just fills in after few seconds. Can we have this fixed ? I am evaluating the library for a new project that I want to use it with.

**Comment by soodrah** [comment]
Hi Fvancop, 
Thanks for this feature. This feature lets me animate portions of data. Except there is a problem that it does not work correctly with animationLeftToRight. I am using animation_lines.html to illustrate the issue. 

Here is the dataSet
var opt1 = {
      animationStartWithDataset : 2,
      animationStartWithData : 7,
      animationLeftToRight:true,
      animationEasing:"linear",
      animationSteps : 200,
      canvasBorders : true,
      canvasBordersWidth : 3,
      canvasBordersColor : "black",
      graphTitle : "default animation",
      legend : true,
      inGraphDataShow : true,
      annotateDisplay : true,
      graphTitleFontSize: 18

}

I would like to animate only from the data point 66  in [35,43,59,,31,50,66]. This works good if i am not using animationLeftToRight. As soon as I use that option the animation for the portion 66 just does not happen instead that portion of the graph just fills in after few seconds. Can we have a fix for this soon, I am evaluating this library for use in a new project. Will appreciate quick turnaround. FYI, I am a very good java developer, just ok in javascript. I am using GWT in my project so will be writing GWT java wrappers for this Library i.e. using JSNI and Java overlay Types. Once done I can make that part of this open source. I am hoping you can fix this so that can use this library. 

Here are the options i am using, taken from animation_lines.html, see the changes to animationStartWithDataset and animationStartWithData

var opt1 = {
      animationStartWithDataset : 2,
      animationStartWithData : 7,
      animationLeftToRight:true,
      animationEasing:"linear",
      animationSteps : 200,
      canvasBorders : true,
      canvasBordersWidth : 3,
      canvasBordersColor : "black",
      graphTitle : "default animation",
      legend : true,
      inGraphDataShow : true,
      annotateDisplay : true,
      graphTitleFontSize: 18

}

**Comment by markosko** [comment]
I think and if i am right u want to animation graph between points 50 and 66? If so then u need to set animationStartWithData, to animationStartWithData : 6, so it will slowly fill graph between points 50 and 66

**Comment by soodrah** [comment]
thanks, replied to Francois

On Sun, Jan 3, 2016 at 4:18 PM, markosko <notifications@github.com> wrote:

> I think and if i am right u want to animation graph between points 50 and
> 66? If so then u need to set animationStartWithData, to
> animationStartWithData : 6, so it will slowly fill graph between points 50
> and 66
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FVANCOP/ChartNew.js/issues/59#issuecomment-168541337>.
>



-- 
Rahul Sood
Software Engineer/Java Developer/Web Developer/C++Programmer/JasperReports
and IText Developer/Expert in J2EE, JSF, HTML, Javascript, EJB2.1 etc.

Work Experience  Includes companies like
Credit Suisse
MICROS (Leader in Hospitality Industry)
Lockheed Martin (Defence Leader)
DUKE Medical Center
Carefirst Blue Cross Blue Shield
C 9195610975
